/**
 * @description Classe de constantes centralisant toutes les valeurs utilisées
 *              dans la logique du trigger Account.
 *              Évite les chaînes de caractères codées en dur dans le code.
 */
public class AccountConstants {
    public static final String MISSION_STATUS_ACTIVE = 'active';
    public static final String MISSION_STATUS_CANCELED = 'canceled';
    public static final String URL_ENDPOINT = 'https://fxyozmgb2xs5iogcheotxi6hoa0jdhiz.lambda-url.eu-central-1.on.aws';

}
